apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: echo
  namespace: flux-system
spec:
  interval: 1m
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system        
  path: ./apps              
  targetNamespace: default
  dependsOn:
    - name: ingress-nginx    
