apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: echo
  namespace: flux-system
spec:
  interval: 1m
  timeout: 5m
  prune: true
  wait: true
  force: true
  sourceRef:
    kind: GitRepository
    name: flux-system          
    namespace: flux-system
  path: ./clusters/kind-demo/apps   
  targetNamespace: default